In [1]:
from givens_angles import *

In [2]:
r = np.arange(-2, 4, 1)
len(r)

6

In [3]:
r

array([-2, -1,  0,  1,  2,  3])

In [10]:
betas, thetas = giv_angles(12, 6, 8, -5, 3/2, r=r)

[ 1.00000000e+00+6.70005140e-17j  8.32667268e-17+5.26209572e-18j
 -1.11022302e-16+8.18973084e-18j -5.55111512e-17+1.61056673e-17j
 -1.15572504e-17-1.86452960e-17j -1.09211504e-19+2.59711169e-19j]


In [11]:
np.array(betas)

array([ 2.0943951 ,  0.78539816, -0.52359878, -1.83259571, -3.14159265,
        1.83259571])

In [12]:
np.array(thetas)

array([-0.10794678, -0.25917693, -0.58569248, -1.0800754 , -1.44720618])

In [ ]:
import numpy as np

def get_coeff(N, J, h, k, x, xp, sigma):
    nk = np.arange(-N+1, N+1, 2)
    coeff = 0.0
    for i in range(len(nk)):
        kp = nk[i] * np.pi / N
        phi_k = np.arctan(J * np.sin(kp) / (h - J * np.cos(kp)))
        sec = 1/np.cos(phi_k)
        gauss = np.exp(-np.abs(kp - k)**2 / (4*sigma**2))
        coeff += np.exp(-1j * kp * (xp - x)) * gauss * sec
    return coeff

# Create Given's rotation matrix
def Giv_Mat(N_s, theta, s):
    mat = np.identity(N_s, dtype=float)
    mat[s-1, s-1] = np.cos(theta)
    mat[s-1, s] = -np.sin(theta)
    mat[s, s-1] = np.sin(theta)
    mat[s, s] = np.cos(theta)
    return mat

In [181]:
N = 16
k = -7 * np.pi / N
x = 11
J = 0.5
h = 1
sigma = 0.75

coeffs = np.zeros((N), dtype=complex)
for xp in range(N):
    coeffs[xp] = get_coeff(N, J, h, k, x, xp, sigma)

coeffs = np.array(coeffs)
coeffs /= np.linalg.norm(coeffs)

coeffs

array([-1.79850875e-03-0.0119716j ,  2.26318470e-03+0.01453034j,
       -6.51332377e-04-0.01231959j, -3.25983445e-16+0.01290829j,
        6.51332377e-04-0.01231959j, -2.26318470e-03+0.01453034j,
        1.79850875e-03-0.0119716j , -9.79055169e-03+0.02254551j,
       -8.11342921e-03-0.00669909j, -1.10901973e-01-0.02534715j,
        1.23799936e-01-0.45009225j,  7.31895682e-01+0.j        ,
        1.23799936e-01+0.45009225j, -1.10901973e-01+0.02534715j,
       -8.11342921e-03+0.00669909j, -9.79055169e-03-0.02254551j])

In [182]:
betas = [-np.angle(coeff) for coeff in coeffs]
p = np.diag(np.exp(1j * np.array(betas)))

coeffs = p @ coeffs
thetas = []
for i in range(N - 1):
    j = N - 1 - i
    theta = np.arctan(-np.abs(coeffs[j]) / np.abs(coeffs[j-1]))
    thetas.append(theta)
    coeffs = Giv_Mat(N, theta, j) @ coeffs
print(coeffs)

[ 1.00000000e+00-3.74339125e-20j -1.05508404e-16-6.51022183e-19j
 -2.79474855e-17-4.34394240e-19j  1.06835184e-16-1.09066399e-19j
  6.43632326e-17-2.58112304e-20j  9.38744500e-17+1.19205457e-18j
 -7.56223500e-17+1.73434254e-18j  6.14257656e-18+1.08412264e-18j
 -5.34332413e-17+3.47049673e-18j  1.04992522e-16+8.98930257e-22j
  8.02305281e-17+9.78352955e-21j  6.38173856e-17+4.72224395e-17j
  3.45817649e-17+3.38943950e-17j  1.74003021e-18-9.40267120e-18j
 -2.44651939e-18+3.10490845e-18j  0.00000000e+00+1.36531932e-18j]


In [183]:
for theta in thetas:
    print(theta)

-1.1663318520236712
-0.23083592452381746
-0.24530015120944038
-0.5816216378192097
-1.0811501945945567
-1.4566782071470612
-1.5602649758201765
-1.5461995608164998
-1.5586837296265619
-1.5560841239465213
-1.5584550128637873
-1.5578843495190648
-1.5584569811667301
-1.5560891815480875
-1.5586900911843102


In [184]:
for beta in betas:
    print(beta)

1.7199124849443224
-1.416282061458729
1.6236168041196497
-1.5707963267949219
1.517975849470105
-1.7253105921310685
1.42168016864549
-1.9804817092445473
2.4513886106518012
2.9168975367126575
1.3023793696025325
-0.0
-1.3023793696025325
-2.9168975367126575
-2.4513886106518012
1.9804817092445473
